package wml;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;

public class ArgParser {
	public boolean showLogs = false;
	public boolean showParseLogs = false;
	public Path dataPath;
	public InputStream in = null;
	
	// TODO this should be autogenerated
	private final String USAGE_STRING = """
		Usage: java wml.Preprocessor [-log|-log-t[oken]|-log-p[arse]|-i[nput] filename|-help|-?]
		Options:
			-datadir		Absolute Path to Wesnoth's data directory
			-log			Print all logs (parser and tokenizer)
			-log-parse		Print parser logs only
			-log-token		Print tokenizer logs only
			-input filename	Preprocess given file
			-help/-?		Print this help
	""";
	
	public void parseArgs(String[] args) {
		for (int i = 0; i < args.length; i++) {
			String arg = args[i];
			if (arg.startsWith("--")) {
				arg = arg.substring(2, arg.length());
			} else if (arg.startsWith("-") || arg.startsWith("/")) {
				arg = arg.substring(1, arg.length());
			}
			
			switch(arg) {
				case "datadir" -> { dataPath = Path.of(args[++i]); }
				case "log" -> { showLogs = true; showParseLogs = true; }
				case "log-token", "log-t" -> showLogs = true;
				case "log-parse", "log-p" -> showParseLogs = true;
				case "help","?" -> System.out.println(USAGE_STRING);
				case "i", "input" -> {
					try {
						in = Files.newInputStream(Path.of(args[++i]));
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}
		}
	}
}
