# This workflow will build a package using Maven
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: [push]

jobs:
  build-linux:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B -X package --file pom.xml

    - uses: actions/upload-artifact@v4
      with:
        name: maptracker.jar
        path: "./jar/maptracker.jar"
        
    - uses: actions/upload-artifact@v4
      with:
        name: maptracker.deb
        path: "./*.deb"
        
  build-windows:

    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B -X package --file pom-windows.xml
      
    - name: Show Directory Contents
      run: dir
        
    - uses: actions/upload-artifact@v4
      with:
        name: maptracker-win.jar
        path: "./jar/maptracker.jar"
        
    - uses: actions/upload-artifact@v4
      with:
        name: maptracker.msi
        path: "./*.msi"
